import dsgame from "../assets/images/projects/dsgame.png";
import cv from "../assets/images/projects/cvmaker.png";
import bts from "../assets/images/projects/battleship.png";
import butterfingers from "../assets/images/projects/butterfingers.png";
//TODO fill with real data set
const projectsData = [
  {
    id: "ButterFingers",
    title: "ButterFingers",
    image: butterfingers,
    video: "",
    description: [
      "Custom made smooth typing input that displays live errors.",
      "Different typing modes, such as 'time', 'words', 'quote'.",
      "Multiplayer 1v1 mode to play against your friends.",
      "Fetches Random quotes using 'quotable' API.",
      "Results after typing is done, including WPM, Accuracy, Errors, Interactive Dashboard.",
      "User can customize the app to their liking.",
      "Various app color themes.",
      "User can create account that will be saved on database, including Google OAuth & GitHub OAuth.",
      "Personal stats, history and customizations will be saved to the account.",
    ],
    tags: [
      "React",
      "TypeScript",
      "Sass",
      "Node.js",
      "Express",
      "MongoDB",
      "Mongoose",
      "Google OAuth",
      "GitHub OAuth",
    ],
    demo: "butterfingers.vercel.app",
    code: "",
    color: "254, 105, 105",
    colorLight: "rgba(254, 105, 105, .125)",
  },
  {
    id: "MustDoIt",
    title: "Must-Do-It",
    image: "mustDoIt",
    video: "",
    description: [
      "Full-stack to-do list app with modern UI/UX.",
      "State management using Redux Toolkit for seamless task handling.",
      "CRUD operations for tasks with real-time updates.",
      "JWT-based authentication and bcrypt for password security.",
      "Customizable task filters and priorities.",
      "User-friendly interface optimized for both desktop and mobile.",
      "Data persistence using MongoDB.",
      "Comprehensive testing suite implemented using Mocha.",
    ],
    tags: [
      "React",
      "JavaScript",
      "Redux Toolkit",
      "Node.js",
      "Express",
      "MongoDB",
      "JWT",
      "Mocha",
    ],
    demo: "mustdoit.vercel.app",
    code: "",
    color: "255, 183, 77",
    colorLight: "rgba(255, 183, 77, .125)",
  },
  {
    id: "BroLog",
    title: "Bro-log",
    image: "broLog",
    video: "",
    description: [
      "Full-stack blogging platform with dedicated CMS for managing content.",
      "JWT-based authentication with secure API endpoints.",
      "Rich text editor for creating and editing blogs.",
      "SEO-friendly architecture with dynamic meta tags.",
      "Interactive blog filtering and sorting by tags or categories.",
      "Real-time comments and likes system.",
      "Responsive and intuitive design optimized for all devices.",
      "Personalized user dashboards with saved articles and history.",
    ],
    tags: [
      "React",
      "TypeScript",
      "Node.js",
      "Express",
      "MongoDB",
      "JWT",
      "Axios",
      "Tailwind CSS",
    ],
    demo: "bro-log.vercel.app",
    code: "",
    color: "100, 149, 237",
    colorLight: "rgba(100, 149, 237, .125)",
  },
  {
    id: "DarkSoulsMemory",
    title: "Dark Souls Memory Game",
    image: "darkSoulsMemory",
    video: "",
    description: [
      "Themed memory game based on Dark Souls characters and lore.",
      "3D-styled cards with dynamic flipping animations.",
      "Multiple difficulty levels for varying challenges.",
      "Sound effects and a custom Dark Souls-inspired playlist.",
      "Responsive design for seamless gameplay on all devices.",
      "Leaderboard to track player scores and compare with friends.",
      "Integrated REST API to fetch game data and save progress.",
    ],
    tags: ["React", "TypeScript", "Node.js", "Express", "Sass", "MongoDB"],
    demo: "darksoulsmemory.vercel.app",
    code: "",
    color: "88, 24, 69",
    colorLight: "rgba(88, 24, 69, .125)",
  },
  {
    id: "ShopEasy",
    title: "ShopEasy",
    image: "shopEasy",
    video: "",
    description: [
      "Full-stack e-commerce platform with dynamic product catalog.",
      "PayPal integration for secure payments.",
      "Cart functionality with seamless checkout experience.",
      "User authentication system with JWT and OAuth support.",
      "Admin dashboard for managing products, orders, and users.",
      "Fully responsive design with Tailwind CSS.",
      "Efficient API handling using Axios.",
      "Database-backed product filtering and search.",
    ],
    tags: [
      "React",
      "TypeScript",
      "Node.js",
      "Express",
      "MongoDB",
      "PayPal API",
      "Tailwind CSS",
      "JWT",
    ],
    demo: "shopeasy.vercel.app",
    code: "",
    color: "46, 204, 113",
    colorLight: "rgba(46, 204, 113, .125)",
  },
  {
    id: "TypingDash",
    title: "Typing Dashboard",
    image: "typingDash",
    video: "",
    description: [
      "Interactive typing app inspired by Monkeytype.",
      "Real-time error highlighting and WPM calculation.",
      "Multiple typing modes: timed, words, and custom quotes.",
      "Custom themes and layouts for enhanced user experience.",
      "Responsive dashboard with typing history and statistics.",
      "Google OAuth for quick login and account integration.",
      "Backend-powered by Node.js and Express with MongoDB for data storage.",
    ],
    tags: [
      "React",
      "TypeScript",
      "Node.js",
      "Express",
      "MongoDB",
      "Tailwind CSS",
      "Google OAuth",
    ],
    demo: "typingdash.vercel.app",
    code: "",
    color: "241, 196, 15",
    colorLight: "rgba(241, 196, 15, .125)",
  },
];
export default projectsData;
