import dsgame from "../assets/images/projects/dsgame.png";
import cv from "../assets/images/projects/cvmaker.png";
import bts from "../assets/images/projects/battleship.png";
import butterfingers from "../assets/images/projects/butterfingers.png";
import ecommerce from "../assets/images/projects/ecommerce.png";
import broLog from "../assets/images/projects/brolog.png";
import mustdoit from "../assets/images/projects/mustdoit.png";
//TODO fill with real data set
const projectsData = [
  {
    id: "ButterFingers",
    title: "ButterFingers",
    image: butterfingers,
    video: "",
    description: [
      "Custom made smooth typing input that displays live errors.",
      "Different typing modes, such as 'time', 'words', 'quote'.",
      "Multiplayer 1v1 mode to play against your friends.",
      "Fetches Random quotes using 'quotable' API.",
      "Results after typing is done, including WPM, Accuracy, Errors, Interactive Dashboard.",
      "User can customize the app to their liking.",
      "Various app color themes.",
      "User can create account that will be saved on database, including Google OAuth & GitHub OAuth.",
      "Personal stats, history and customizations will be saved to the account.",
    ],
    tags: [
      "React",
      "TypeScript",
      "Sass",
      "Node.js",
      "Express",
      "MongoDB",
      "Mongoose",
      "Google OAuth",
      "GitHub OAuth",
    ],
    demo: "butterfingers.vercel.app",
    code: "https://github.com/jet-black-ninja/butterfingers2-frontend",
    color: "254, 105, 105",
    colorLight: "rgba(254, 105, 105, .125)",
  },
  {
    id: "e-Commerce",
    title: "E-commerce",
    image: ecommerce,
    video: "",
    description: [
      "Full-stack e-commerce platform with dynamic product catalog.",
      "PayPal integration for secure payments.",
      "Cart functionality with seamless checkout experience.",
      "User authentication system with JWT ",
      "Admin dashboard for managing products, orders, and users.",
      "Fully responsive design with ShadCn/UI and Tailwind CSS.",
      "Efficient API handling using Axios.",
      "Database-backed product filtering and search.",
    ],
    tags: [
      "React",
      "TypeScript",
      "Node.js",
      "Express",
      "MongoDB",
      "PayPal API",
      "Tailwind CSS",
      "JWT",
    ],
    demo: "https://ecommerce-frontend-ts-tw-shcnui.vercel.app/auth/login",
    code: "https://github.com/jet-black-ninja/ecommerce-frontend",
    color: "46, 204, 113",
    colorLight: "rgba(46, 204, 113, .125)",
  },
  {
    id: "BroLog",
    title: "Bro-log",
    image: broLog,
    video: "",
    description: [
      "Full-stack blogging platform with dedicated CMS for managing content.",
      "JWT-based authentication with secure API endpoints.",
      "Rich text editor for creating and editing blogs.",
      "SEO-friendly architecture with dynamic meta tags.",
      "Interactive blog filtering via text search and sorting by tags or categories.",
      "Real-time comments and likes system.",
      "Responsive and intuitive design optimized for all devices.",
      "Personalized user dashboards with saved articles and history.",
    ],
    tags: [
      "React",
      "TypeScript",
      "Node.js",
      "Express",
      "MongoDB",
      "JWT",
      "Axios",
      "Tailwind CSS",
    ],
    demo: "bro-log.vercel.app",
    code: "",
    color: "100, 149, 237",
    colorLight: "rgba(100, 149, 237, .125)",
  },
  {
    id: "MustDoIt",
    title: "Must-Do-It",
    image: mustdoit,
    video: "",
    description: [
      "Full-stack to-do list app with modern UI/UX.",
      "State management using Redux Toolkit for seamless task handling.",
      "CRUD operations for tasks with real-time updates.",
      "JWT-based authentication and bcrypt for password security.",
      "Customizable task filters and priorities.",
      "Data persistence using MongoDB.",
      "Comprehensive testing suite implemented using Mocha.",
    ],
    tags: [
      "React",
      "JavaScript",
      "Redux Toolkit",
      "Node.js",
      "Express",
      "MongoDB",
      "JWT",
      "Mocha",
    ],
    demo: "https://jet-black-ninja.github.io/to-do-list/dist/index.html",
    code: "https://github.com/jet-black-ninja/to-do-list",
    color: "255, 183, 77",
    colorLight: "rgba(255, 183, 77, .125)",
  },
  {
    id: "DarkSoulsMemory",
    title: "Dark Souls Memory Game",
    image: dsgame,
    video: "",
    description: [
      "Themed memory game based on Dark Souls characters and lore.",
      "3D-styled cards with dynamic flipping animations.",
      "Multiple difficulty levels for varying challenges.",
      "Sound effects and a custom Dark Souls-inspired playlist.",
      "Responsive design for seamless gameplay on all devices.",
    ],
    tags: ["React", "TypeScript", "Node.js", "Sass"],
    demo: "https://ds-memory-game-47ij.vercel.app/",
    code: "https://github.com/jet-black-ninja/ds-memory-game",
    color: "88, 24, 69",
    colorLight: "rgba(88, 24, 69, .125)",
  },

  {
    id: "cv-maker",
    title: "CV Maker",
    image: cv,
    video: "",
    description: [
      "User-friendly interface that makes it easy to create a custom CV",
      "Add and edit sections such as personal information, education background, work experience, skills, and achievements--with an option to include custom sections",
      "Preview your CV at any time to make sure it looks presentable and fitting to your needs",
      "Responsive design that allows you to create a CV even through your phone",
    ],
    tags: ["React", "Vite", "Google OAuth"],
    demo: "https://cv-maker-h3pk.vercel.app/",
    code: "https://github.com/jet-black-ninja/CV-maker",
    color: "241, 196, 15",
    colorLight: "rgba(241, 196, 15, .125)",
  },
  {
    id: "battleship-game",
    title: "Battleship Game",
    image: bts,
    video: "",
    description: [
      "Classic battleship game recreated with an intuitive and engaging interface",
      "Single-player mode against an AI with varying difficulty levels",
      "Interactive drag-and-drop ship placement for a seamless setup experience",
      "Responsive design for smooth gameplay on both desktop and mobile devices",
      "Customizable grid sizes and ship types for added variety and challenge",
    ],
    tags: ["JavaScript", "HTML", "SASS"],
    demo: "https://jet-black-ninja.github.io/BattleShip/dist/index.html",
    code: "https://github.com/jet-black-ninja/BattleShip",
    color: "52, 152, 219",
    colorLight: "rgba(52, 152, 219, .125)",
  },
];
export default projectsData;
